// File generated by FlutterFire CLI.
// Do not modify this file, it will be overwritten where running `flutterfire configure`.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdooWtPdtgytKqGw0FneBMhoNPyFLoS2U',
    appId: '1:28475506464:web:782c4974a284d18f2c6145',
    messagingSenderId: '28475506464',
    projectId: 'running-app-uni',
    authDomain: 'running-app-uni.firebaseapp.com',
    storageBucket: 'running-app-uni.firebasestorage.app',
    measurementId: 'G-7GKEG48RPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcd9IJcaH18idl5wfLHnkNSuEuPZA5ak',
    appId: '1:28475506464:android:2c5177b4c28647ee2c6145',
    messagingSenderId: '28475506464',
    projectId: 'running-app-uni',
    storageBucket: 'running-app-uni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPwVrCaxrIwm8rAYTqtVqKWUe5x18h4A',
    appId: '1:28475506464:ios:5e701cdec12ee8302c6145',
    messagingSenderId: '28475506464',
    projectId: 'running-app-uni',
    storageBucket: 'running-app-uni.firebasestorage.app',
    iosBundleId: 'com.example.running',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPwVrCaxrIwm8rAYTqtVqKWUe5x18h4A',
    appId: '1:28475506464:ios:5e701cdec12ee8302c6145',
    messagingSenderId: '28475506464',
    projectId: 'running-app-uni',
    storageBucket: 'running-app-uni.firebasestorage.app',
    iosBundleId: 'com.example.running',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdooWtPdtgytKqGw0FneBMhoNPyFLoS2U',
    appId: '1:28475506464:web:1beaf918fc2e62642c6145',
    messagingSenderId: '28475506464',
    projectId: 'running-app-uni',
    authDomain: 'running-app-uni.firebaseapp.com',
    storageBucket: 'running-app-uni.firebasestorage.app',
    measurementId: 'G-5V28JJCBSJ',
  );

}